### ISSUE TITLE
Possible update for new backpack.tf UI?

### ISSUE THREAD

**Issue by JetpackJackson** [HairGMan/bptf-killstreak-kit-additions#1]
Hi, I absolutely love this addon, it works great. Are you planning on eventually releasing a version/update that works with the new UI that the backpack.tf people are working on? I know it's still in beta and everything, but I just figured I'd ask and see.

**Comment by HairGMan** [comment]
Hi! sorry for taking like 4 months to give you a response, I basically haven't been paying attention to either backpack.tf nor this repo since the beggining of this year, so I didn't even find out about the new UI until last week. I have to familiarize myself with it yet, been hesitant to use it since other userscripts haven't transitioned to it either, but I'm probably gonna give it a shot if I ever find some time, that said whenever it becomes the default for the website I'll most likely release a version for it if the script's still needed.
Also thanks for the kind words! I'm very glad you liked it. If you're reading this, make sure to update it since I did some minor bugfixes.

**Comment by JetpackJackson** [comment]
No worries! I'll make sure to update the script. Thanks again for making this script!
